feat: add acpi
deepin-community/acpi pull request #1
Opened 2023-07-07 07:11 UTC by Udacv

Acpi shows the information of the ACPI device.

Log: add acpi
Issue: https://github.com/deepin-community/Repository-Manager/pull/95

2023-07-07 09:04 UTC, Zeno-sole commented
source/format 应该改成native格式

2023-07-07 09:19 UTC, Udacv commented
> source/format 应该改成native格式

好的老师

2023-07-07 09:27 UTC, Udacv commented
@chenchongbiao

2023-07-07 09:31 UTC, UTsweetyfish commented
这个是自行打包的？

2023-07-07 09:32 UTC, Udacv commented
> 这个是自行打包的？

这个是在debian仓库中有的而在deepin仓库中没有的软件包列表中找到的，我就打包了

2023-07-07 09:34 UTC, UTsweetyfish requested changes
以及，自行打包是因为？

2023-07-07 09:34 UTC, UTsweetyfish commented on debian/control
> +Standards-Version: 1.6
Standards-Version 不是软件包版本，是 Debian Policy 的版本

2023-07-07 09:34 UTC, UTsweetyfish commented on debian/control
> +Homepage: https://github.com/deepin-community/acpi
Homepage 是上游项目链接

2023-07-07 09:34 UTC, UTsweetyfish commented on debian/source/format
> +3.0 (native)
不应该是 native 吧？

2023-07-07 09:34 UTC, UTsweetyfish commented
> > 这个是自行打包的？
> 
> 这个是在debian仓库中有的而在deepin仓库中没有的软件包列表中找到的，我就打包了

可以从 debian 那边导入

2023-07-07 09:35 UTC, UTsweetyfish commented
> source/format 应该改成native格式

自研项目才应该 native，这里应该是 quilt，然后 changelog 改成带 debian_version 的吧

2023-07-07 09:36 UTC, Udacv commented on debian/source/format
> +3.0 (native)
这个好像是因为没有orig部分，老师跟我说药用native

2023-07-07 09:37 UTC, Udacv commented
> 

好的好的我看下

2023-07-07 09:59 UTC, UTsweetyfish requested changes
copyright 文件也要改下

2023-07-07 09:59 UTC, UTsweetyfish commented on debian/control
> +Homepage: https://packages.debian.org/source/sid/acpi
```suggestion
Homepage: http://sourceforge.net/projects/acpiclient
```

2023-07-07 09:59 UTC, UTsweetyfish commented on debian/changelog
> +acpi (1.6) unstable; urgency=medium
```suggestion
acpi (1.6-1) unstable; urgency=medium
```

2023-07-10 01:15 UTC, Udacv commented
> copyright 文件也要改下

修改好啦

2023-07-10 02:38 UTC, Zeno-sole commented
/approve

2023-07-10 02:39 UTC, merged